- name: Configure rsyslogd
  notify:
    - reload rsyslog
  tags: rsyslog
  template: src=templates/rsyslog/alertlogic.conf dest=/etc/rsyslog.d/alertlogic.conf owner=root group=root mode=0644
  when: rsyslog_init_exists|success

